services:
  - type: web
    name: selenium-flask-app  # Your service name
    env: docker  # Use "docker" for a Docker-based deployment
    dockerfilePath: Dockerfile  # Path to your Dockerfile in the root directory
    plan: free  # Define your Render plan
    envVars:
      - key: PORT
        value: 5000  # Ensures Flask or Gunicorn listens on the correct port
